### ISSUE TITLE
Leverage the Default trait

### ISSUE THREAD

**Issue by dwijnand** [matklad/typed_key#4]
Given the presence of the `Default` trait in the Rust's std/core and the adoption in the ecosystem I wonder if you'd considered making that a type bound of defining a key.

By adding this requirement you would make the consumption-side of the API simpler because the result type wouldn't need to be `Result` or `Option`.

I don't have time to experiment this idea myself at this time, so I opened an issue instead to see what you think.

**Comment by matklad** [comment]
The cool thing about the `Key` is that the user can add all interesting bounds.

For example, `Key` says nothing about `Deserialize`, and the serde example adds this bound itself:

https://github.com/matklad/typed_key/blob/c785381d103fcf08e7cfb6815cd6eed9be68516b/examples/serde.rs#L25
 
Similarly, the `any` example adds `: Any` bound to both `put` and `get` sides of the API:

https://github.com/matklad/typed_key/blob/c785381d103fcf08e7cfb6815cd6eed9be68516b/examples/any.rs#L22-L31

So, the user already can add `fn get<T: Default>(&self, key: Key<T>) -> T` method themselves. 

I also would worry about adding `Default` requirement per se, because sometimes it is important to distinguish between `0` and `no value`, for example. If you don't use defaults, the client can easily `.unwrap_or_default()` on the call site. If you do use defaults, the client plainly can't reliably distinguish between missing value and a default. 

So, closing this issue as something already possible, and something which should be implemented by consumer, if needed, and not in the library itself!

**Comment by dwijnand** [comment]
Oh yeah, you're right (of course). I hadn't realised where the crate finished and the serde use case picked up. Awesome.

> I also would worry about adding Default requirement per se, because sometimes it is important to distinguish between 0 and no value, for example. If you don't use defaults, the client can easily .unwrap_or_default() on the call site. If you do use defaults, the client plainly can't reliably distinguish between missing value and a default.

Indeed, the need to identify if a key is set or not would most probably need to be handled. But (at least in my experience) that tends to be a niche need, and therefore it's advantageous to make default-selecting less verbose.

As an aside, is `Option` free or quasi-free in Rust? (It's very not-free in Scala).

**Comment by matklad** [comment]
>As an aside, is Option free or quasi-free in Rust?

The cost is negligible. You need to store "is this none?" flag somewhere, so you need at least an extra byte. However, in Rust every type is value type, so this is indeed just a byte + maybe alignment, and not a separate allocation with object header and indirection, as in Scala. Moreover, certain types like pointers and references are marked as non-zero. That means that compiler knows that a bit-pattern of all zeros is not a valid value of a type, and could use zero as a special flag. And that guarantees that things like `Option<Box<T>>` or `Option<&T>` don't need extra storage at all:

https://play.rust-lang.org/?gist=b7a4753ba13254c05a02208d71f84837&version=stable&mode=debug


What you can't do currently is mark some values of existing type as invalid, and make compiler use them as a flag. That is, it is impossible to make `Option<u32>` such that `None` is represented as `u32::max_value()`, you need to write custom code for that. 

>But (at least in my experience) that tends to be a niche need, and therefore it's advantageous to make default-selecting less verbose.

Interesting! At least in my experience, Rust differs from many languages in that not having a default value of a type is actually quite feasible. In C++, types without defaults are possible, but are awkward to use with the standard library, and supporting move semantics mandates some special state for a "moved out from" object anyway. In languages with constructors, like Java and, to a lesser extent, Kotlin and Scala, the defaults are forced onto you because constructor's code has to witness the object in *some* state (In general, constructors look like an exceptionally awful idea, and looks like I should write another blog post about it =/). 


In contrast, in Rust moves are handled by the language, there are no constructors at all, and, totally awesome, a true control flow analysis is used to track initialization of local variables: https://play.rust-lang.org/?gist=dc4bebcc678b462b88d55a1635e2e1aa&version=stable&mode=debug.

**Comment by dwijnand** [comment]
Thanks!

I welcome you blogging about constructors, because I didn't get what you meant by witnessing.

A+ for illustrating your points with playpen gists! :smiley:
